name: Repo add packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman-key --init
        pacman-key --populate
        pacman -Syyu --noconfirm base-devel git devtools archiso mkinitcpio-archiso docker docker-buildx

    - name: repo-add
      run: |
        cd x86_64/
        chmod +x ./update-db.sh
        ./update-db.sh
