name: Repo add packages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 8 */4 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman-key --init
        pacman-key --populate
        pacman -Syyu --noconfirm base-devel git devtools archiso mkinitcpio-archiso docker docker-buildx

    - name: repo-add
      run: |
        chmod +x ./x86_64/update-db.sh
        ./x86_64/update-db.sh 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Add built packages"
        git push
